In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
import random 


In [121]:
class Modulator():
    def __init__(self, M):
        self.M = M
        self.k = int(np.log2(M)) 

    def dec2bin(self, x: np.ndarray):
        bins = []
        for dec in x:
            bcw = str(bin(dec)[2:]).zfill(k)
            bins.append(bcw)
        return np.array(bins)

    def bin2dec(self, bins: np.ndarray):
        decs = np.zeros_like(bins, dtype=np.int32)
        for i, b in enumerate(bins):
            decs[i] = int(b, 2)
        return decs


class QAM(Modulator):
    def __init__(self, M=16):
        super().__init__(M)
        self.axis_points = self._make_axis_point(M)
        
        # integer 0 ~ M-1
        self.ip = np.arange(M)

        # decimal to binary (array of string)
        self.ipBin = self.dec2bin(self.ip)
        self.symbols = self._make_symbols()

        # Mapping dictionary for M-QAM modulation
        self.mapping = dict(zip(self.ipBin, self.symbols))

        # Demapping dictionary for M-QAM demodulation 
        self.demapping = {v: k for k, v in self.mapping.items()}

    def __call__(self):
        return self.mapping
 
    def _make_symbols(self):
        # dividing binary into "b0 b1" and "b2 b3"
        ipBin_real = np.array([b[: self.k//2] for b in self.ipBin])
        ipBin_imag = np.array([b[self.k//2 :] for b in self.ipBin])

        # map "b0b1" and "b2b3" to axis_points 
        ipDec_real = self.bin2dec(ipBin_real)
        ipDec_imag = self.bin2dec(ipBin_imag)

        real_points = np.array([self.axis_points[i] for i in ipDec_real])
        imag_points = np.array([self.axis_points[i] for i in ipDec_imag])

        symbols= real_points + 1j * imag_points 
        return symbols
    
    def _make_axis_point(self, M):
        con_min = -(2 * np.sqrt(M) / 2 - 1)
        con_max = (2 * np.sqrt(M) / 2 - 1)
        p_num = int(np.sqrt(M))
        return np.linspace(con_min, con_max, p_num)


In [122]:
modem = QAM(M=16)
modem()

{'0000': (-3-3j),
 '0001': (-3-1j),
 '0010': (-3+1j),
 '0011': (-3+3j),
 '0100': (-1-3j),
 '0101': (-1-1j),
 '0110': (-1+1j),
 '0111': (-1+3j),
 '1000': (1-3j),
 '1001': (1-1j),
 '1010': (1+1j),
 '1011': (1+3j),
 '1100': (3-3j),
 '1101': (3-1j),
 '1110': (3+1j),
 '1111': (3+3j)}

In [111]:
def qam(M=16):
    
    # number of bits in each constellation
    k = int(np.log2(M))

    # making axis points 
    con_min = -(2 * np.sqrt(M) / 2 - 1)
    con_max = 2 * np.sqrt(M) / 2 - 1
    p_num = int(np.sqrt(M))
    axis_points = np.linspace(con_min, con_max, p_num)
    print(axis_points)
    
    # symbol mapping 
    ip = np.arange(M)

    # decimal to binary
    ipBin = dec2bin(ip)

    # dividing binary into "b0 b1" and "b2 b3"
    ipBin_real = np.array([b[: k//2] for b in ipBin])
    ipBin_imag = np.array([b[k//2 :] for b in ipBin])

    # map "b0b1" and "b2b3" to axis_points 
    ipDec_real = bin2dec(ipBin_real)
    ipDec_imag = bin2dec(ipBin_imag)

    real_points = np.array([axis_points[i] for i in ipDec_real])
    imag_points = np.array([axis_points[i] for i in ipDec_imag])

    symbols= real_points + 1j * imag_points 
    return symbols 
    

    



In [112]:
qam()

[-3. -1.  1.  3.]
[0 0 0 0 1 1 1 1 2 2 2 2 3 3 3 3]
[-3. -3. -3. -3. -1. -1. -1. -1.  1.  1.  1.  1.  3.  3.  3.  3.]


array([-3.-3.j, -3.-1.j, -3.+1.j, -3.+3.j, -1.-3.j, -1.-1.j, -1.+1.j,
       -1.+3.j,  1.-3.j,  1.-1.j,  1.+1.j,  1.+3.j,  3.-3.j,  3.-1.j,
        3.+1.j,  3.+3.j])

In [99]:
M = 16  # number of constellation points 
k = int(np.log2(M))  # number of bits in each constellation 
k

4

In [13]:
con_min = - ( 2 * np.sqrt(M) / 2 - 1)
con_max = 2 * np.sqrt(M) / 2 - 1
axis_num = int(np.sqrt(M))

In [14]:
re_point = np.linspace(con_min, con_max, axis_num)
im_point = np.linspace(con_min, con_max, axis_num) 

re_point, im_point

(array([-3., -1.,  1.,  3.]), array([-3., -1.,  1.,  3.]))

In [16]:
ip = np.arange(16)
ip

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [61]:
def dec2bin(x: np.ndarray):
    bins = []
    for dec in x:
        bcw = str(bin(dec)[2:]).zfill(4)
        bins.append(bcw)
    return np.array(bins)

def bin2dec(bins: np.array):
    decs = np.zeros_like(bins, dtype=np.int32)
    for i, b in enumerate(bins):
        decs[i] = int(b, 2)
    return decs

    



In [60]:
ipBin = dec2bin(ip)
ipBin

ipDec = bin2dec(ipBin)
ipDec

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int32)

In [67]:
ipBin
ipBin_real = np.array([b[:2] for b in ipBin])
ipDec_real = bin2dec(ipBin_real)
point_real = np.array([re_point[i] for i in ipDec_real])
point_real

array([-3., -3., -3., -3., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  3.,
        3.,  3.,  3.])

In [69]:
ipBin
ipBin_imag = np.array([b[2:] for b in ipBin])
ipDec_imag = bin2dec(ipBin_imag)
point_imag = np.array([im_point[i] for i in ipDec_imag])
point_imag

array([-3., -1.,  1.,  3., -3., -1.,  1.,  3., -3., -1.,  1.,  3., -3.,
       -1.,  1.,  3.])

In [70]:
symbols = point_real + 1j * point_imag

In [71]:
symbols

array([-3.-3.j, -3.-1.j, -3.+1.j, -3.+3.j, -1.-3.j, -1.-1.j, -1.+1.j,
       -1.+3.j,  1.-3.j,  1.-1.j,  1.+1.j,  1.+3.j,  3.-3.j,  3.-1.j,
        3.+1.j,  3.+3.j])

In [ ]:
ipBin
ipBin_real = np.array([b[:2] for b in ipBin])
ipDec_real = bin2dec(ipBin_real)
point_real = np.array([re_point[i] for i in ipDec_real])
ipBin_imag = np.array([b[2:] for b in ipBin])
ipDec_imag = bin2dec(ipBin_imag)
point_imag = np.array([im_point[i] for i in ipDec_imag])
symbols = point_real + 1j * point_imag



In [102]:
k // 2


2

In [113]:
ipBin

array(['0000', '0001', '0010', '0011', '0100', '0101', '0110', '0111',
       '1000', '1001', '1010', '1011', '1100', '1101', '1110', '1111'],
      dtype='<U4')

In [114]:
symbols

array([-3.-3.j, -3.-1.j, -3.+1.j, -3.+3.j, -1.-3.j, -1.-1.j, -1.+1.j,
       -1.+3.j,  1.-3.j,  1.-1.j,  1.+1.j,  1.+3.j,  3.-3.j,  3.-1.j,
        3.+1.j,  3.+3.j])

In [115]:
dict(zip(ipBin, symbols))

{'0000': (-3-3j),
 '0001': (-3-1j),
 '0010': (-3+1j),
 '0011': (-3+3j),
 '0100': (-1-3j),
 '0101': (-1-1j),
 '0110': (-1+1j),
 '0111': (-1+3j),
 '1000': (1-3j),
 '1001': (1-1j),
 '1010': (1+1j),
 '1011': (1+3j),
 '1100': (3-3j),
 '1101': (3-1j),
 '1110': (3+1j),
 '1111': (3+3j)}